[package]
name = "nostd_structs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nostd_structs"
path = "src/lib.rs"

[dependencies]
